[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"