# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10-rc-stretch

    working_directory: /go/src/github.com/radu-matei/azure-functions-golang-worker
    steps:
      - checkout

      - run: make dep
      - run: make golang-worker
      - run: make samples